# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CommunicationUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_communication(object):
    def setupUi(self, communication):
        communication.setObjectName("communication")
        communication.resize(970, 860)
        self.tabWidget = QtWidgets.QTabWidget(communication)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 971, 861))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(80, 50, 99, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 80, 131, 701))
        self.listWidget.setObjectName("listWidget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(communication)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(communication)

    def retranslateUi(self, communication):
        _translate = QtCore.QCoreApplication.translate
        communication.setWindowTitle(_translate("communication", "Form"))
        self.radioButton.setText(_translate("communication", "Client"))
        self.radioButton_2.setText(_translate("communication", "Server"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("communication", "Socket TCP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("communication", "Socket UDP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("communication", "页"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("communication", "页"))
